인사 내역 등록/20
Backble/originalPopool pull request #21
Opened 2022-06-26 11:13 UTC by sienna011022

기본적인 인사명세(아이디,이름,재직 기간)을 등록하는 기능입니다
-파일 업로드는 구현 중입니다.

2022-06-26 15:35 UTC, Linho1150 commented on Career-Service/src/main/java/kr/co/careerservice/controller/CareerController.java
> +                files.get(i).transferTo(new File("C:\\Test_Popook"+files.get(i).getOriginalFilename()));
파일 업로드 관련 코드로 보입니다 :)
해당 코드는 로컬에서 작동시 동작할 수 있지만 실제서버에서는 작동하지 않을 것으로 보입니다!
저도 스프링에서 파일 업로드 경험이 없지만 최소한 절대경로 대신 상대경로를 사용해야할 듯보입니다 !

2022-06-26 15:37 UTC, Linho1150 commented on Career-Service/src/main/java/kr/co/careerservice/domain/entity/CareerEntity.java
> +@Table(name = "tbl_career")
테이블명 앞에 tbl_을 붙이는건 식별하기는 쉽지만 굳이 필요한가 생각이 듭니다!
저도 아닐 수 있으니 틀리면 알려주세요 :)

2022-06-26 15:43 UTC, Linho1150 commented on Career-Service/src/main/java/kr/co/careerservice/domain/dto/CareerDto.java
> +        private Long careerId;
빈칸이 발생하면 "아이디를 입력해주세요"가 반환되는데 입력하는 값이 Long 타입이란건 아이디는 숫자만 가능하단건가요??

2022-06-26 15:46 UTC, Linho1150 commented
고생 많으셨습니다 성윤님 ! 😊
함께 스프링을 배우는 단계라서 저 또한 코드리뷰가 틀릴 수 도 있으니 참고용으로만 사용해주시면 감사드리겠습니다 : )
불과 저번주까지 JAVA로 데이터베이스를 접근하는 단계에서 바로 Spring으로 접근하신게 멋집니다!

2022-06-27 04:07 UTC, hongdosan commented on Career-Service/src/main/java/kr/co/careerservice/configuration/SwaggerConfiguration.java
> +public class SwaggerConfiguration {
패키지명, infra.config.SwaggerConfig로 동일하게 하는 것이 좋을 것 같아요!

2022-06-27 04:07 UTC, hongdosan commented on Career-Service/src/main/java/kr/co/careerservice/configuration/SwaggerConfiguration.java
> +    public Docket api() {
그리고 아마, 스웨거 테스트 해보려면, WebMvcConfigurer 설정해서 .allowedMethods("GET", "POST", "PUT", "DELETE") 열어줘야 할 것입니다.!

2022-06-27 04:07 UTC, hongdosan commented on Career-Service/src/main/java/kr/co/careerservice/controller/CareerController.java
> +@Controller
Json 데이터를 전달하기 위해 @ResponseBody를 가지고있는 @RestController를 쓰는 것이 더 좋습니다.

2022-06-27 04:07 UTC, hongdosan commented on Career-Service/src/main/java/kr/co/careerservice/controller/CareerController.java
> +    @Autowired
지금 보면, 현재 주입 방식으로 필드 주입 방식과 생성자 주입 방식이 모두 사용되고 있습니다!
Spring 주입 방식으로 3가지 방법이 있는데 차이점을 간단하게 공부하셔야할 것 같습니다.
가장 추천 드리는 방법은 생성자 주입 방법입니다.

2022-06-27 04:07 UTC, hongdosan commented on Career-Service/src/main/java/kr/co/careerservice/domain/entity/CareerEntity.java
> +@Table(name = "tbl_career")
이것은 저도 붙이는 걸 추천드립니다! 테이블 명 앞에 tbl을 붙이는 게 더 좋더라구요!!

2022-06-27 04:07 UTC, hongdosan commented on Career-Service/src/main/java/kr/co/careerservice/domain/entity/CareerEntity.java
> +    private Long careerId;
테이블에서 PK로 Long 타입으로 설정하는 이유가 있고, 그 외 후보키로 또 구분할 수 있는 필드가 있어야 합니다.
여기에 대해서는 Database에 대해 더 공부를 하셔야하는데, 직접 만나서 설명 드리겠습니다.

2022-06-27 04:07 UTC, hongdosan commented on Career-Service/src/main/java/kr/co/careerservice/domain/entity/CareerEntity.java
> +        this.careerId = careerId;
이 PK는 자동으로 값이 생성되게 해야해서, 저희가 임의로 값을 설정하면 안됩니다!!

2022-06-27 04:16 UTC, sienna011022 commented on Career-Service/src/main/java/kr/co/careerservice/domain/dto/CareerDto.java
> +        private Long careerId;
오 제가 식별자  id와 인사에서 사용하는 id를 혼동한것 같습니다! 감사합니다

2022-06-27 06:05 UTC, hsju0202 requested changes

2022-06-27 06:05 UTC, hsju0202 commented on Career-Service/src/main/java/kr/co/careerservice/service/careerServiceImpl.java
> +public class careerServiceImpl implements careerService{
클래스명은 시작은 대문자!

2022-06-27 06:05 UTC, hsju0202 commented on Career-Service/src/main/java/kr/co/careerservice/service/careerService.java
> +public interface careerService {
클래스명 시작은 대문자가 관례입니다!

2022-06-27 06:05 UTC, hsju0202 commented on Career-Service/src/main/java/kr/co/careerservice/domain/entity/CareerEntity.java
> +    private String grade;
notion 기능정의서에 grade는 gold, sliver, bronze, black이 정해져 있는 것 같은데 String 타입이 아닌 Enum 타입으로 정의하는건 어떨까요??

2022-06-27 06:05 UTC, hsju0202 commented on Member-Service/src/main/java/kr/co/memberservice/service/MemberMstServiceImpl.java
> +            MemberMstEntity memberMstEntity = MemberMstEntity.builder()
탭이 들어가면서 충돌이 나는 것 같습니다

2022-06-27 06:05 UTC, hsju0202 commented on Member-Service/src/main/java/kr/co/memberservice/service/MemberMstServiceImpl.java
> +                )))
여기는 줄바꿈!

2022-06-27 06:07 UTC, Linho1150 commented on Career-Service/src/main/java/kr/co/careerservice/domain/entity/CareerEntity.java
> +@Table(name = "tbl_career")
@HyuckJuneHong 피드백 감사합니다 :)
혹시 왜 좋은지도 알려주실 수 있을까요?

2022-06-27 09:43 UTC, HyuckJuneHong commented on Career-Service/src/main/java/kr/co/careerservice/domain/entity/CareerEntity.java
> +@Table(name = "tbl_career")
@Linho1150 무조건적으로 정해진 것은 아니지만 테이블 명으로 앞에 "tbl_" 이나 "t_"를 붙여주는게 하나의 약속이라고 알고 있습니다!
제 주변 지인들도 대다수가 현재 그렇게 하고 있구요!!

2022-06-27 09:44 UTC, HyuckJuneHong commented on Career-Service/src/main/java/kr/co/careerservice/domain/entity/CareerEntity.java
> +    private String grade;
맞아요 맞아요 저도 그걸 추천드립니다 ㅎ

2022-06-27 10:36 UTC, sienna011022 commented on Career-Service/src/main/java/kr/co/careerservice/controller/CareerController.java
> +                files.get(i).transferTo(new File("C:\\Test_Popook"+files.get(i).getOriginalFilename()));
어쩐지.....저장이 안되더라고요 ㅎㅎ 감사합니다

2022-06-27 10:37 UTC, sienna011022 commented on Career-Service/src/main/java/kr/co/careerservice/configuration/SwaggerConfiguration.java
> +public class SwaggerConfiguration {
넵 알겠습니다!

2022-06-27 10:41 UTC, sienna011022 commented on Career-Service/src/main/java/kr/co/careerservice/domain/entity/CareerEntity.java
> +    private String grade;
아 이게 현재는 등급을 사용자가 입력하게 되어있는데. 원래는 다른 평가자가 평가를 입력하고 환산해서 등급을 반환하면 그 값을 데이터베이스에 넣으려고 한거거든요. 근데 평가 기능을 구현 안해서 일단은 등급을 사용자가 입력하게 해놔서 차후에 enum으로 고칠 예정입니다

2022-06-27 10:41 UTC, sienna011022 commented on Career-Service/src/main/java/kr/co/careerservice/service/careerService.java
> +public interface careerService {
감사합니닷!

2022-06-27 10:45 UTC, sienna011022 commented on Career-Service/src/main/java/kr/co/careerservice/configuration/SwaggerConfiguration.java
> +    public Docket api() {
어쩐지 안되더라고요 ㅎㅎ감사합니다!

2022-06-29 13:37 UTC, Linho1150 commented on Career-Service/src/main/java/kr/co/careerservice/domain/entity/CareerEntity.java
> +@Table(name = "tbl_career")
@HyuckJuneHong 오 그렇군요 감사합니다 :)

2022-06-30 08:54 UTC, closed without merging